openapi: 3.0.0
info:
  title: API Musicas
  description: Esta API tem como função descobrir as músicas de cada autor
  contact:
    name: Grupo05
    email: grupo05@ismai.pt
  version: 0.0.1
servers:
- url: http://localhost:8080
  description: My localhost
  variables:
    basePath:
      default: /
paths:
  /Musica:
    get:
      tags:
      - Musicas
      summary: All Musicas
      operationId: allMusicas
      responses:
        "200":
          description: Array of all Musicas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Musica'
                x-content-type: application/json
            application/xml:
              schema:
                $ref: '#/components/schemas/inline_response_200_Musica'
      x-swagger-router-controller: Musicas
    post:
      tags:
      - Musicas
      summary: Create Musica
      operationId: createMusica
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Musica'
            examples:
              MusicaExample01:
                $ref: '#/components/examples/MusicaExample01'
              MusicaExample02:
                $ref: '#/components/examples/MusicaExample02'
          application/xml:
            schema:
              $ref: '#/components/schemas/Musica'
            examples:
              MusicaExample01:
                $ref: '#/components/examples/MusicaExample01'
              MusicaExample02:
                $ref: '#/components/examples/MusicaExample02'
      responses:
        "200":
          description: Create a Musica
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Musica'
            application/xml:
              schema:
                $ref: '#/components/schemas/Musica'
        "400":
          description: Bad request
      x-swagger-router-controller: Musicas
  /Musica/{id}:
    get:
      tags:
      - Musicas
      summary: retrieve Musica with ID
      operationId: retrieveMusicaID
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Retrieve Musica id 1
            value: 1
          two:
            summary: Retrieve Musica id 2
            value: 2
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Musica'
            application/xml:
              schema:
                $ref: '#/components/schemas/Musica'
        "400":
          description: Bad request
        "404":
          description: id not found
      x-swagger-router-controller: Musicas
    put:
      tags:
      - Musicas
      summary: Update Musica
      operationId: updateMusica
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Update Musica id 1
            value: 1
          two:
            summary: Update Musica id 2
            value: 2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Musica'
            examples:
              Example01:
                $ref: '#/components/examples/MusicaExample01'
              Example02:
                $ref: '#/components/examples/MusicaExample02'
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                description: Musica PUT success
                x-content-type: application/json
        "400":
          description: Bad request
        "404":
          description: id not found
      x-swagger-router-controller: Musicas
    delete:
      tags:
      - Musicas
      summary: Delete Musica
      operationId: deleteMusica
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Delete Musica id 1
            value: 1
          two:
            summary: Delete Musica id 2
            value: 2
      responses:
        "204":
          description: No Content
        "404":
          description: id not found
      x-swagger-router-controller: Musicas
  /Albums/{id}/Musica:
    get:
      tags:
      - Albums
      summary: Show Album with ID
      operationId: albumMusicID
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Retrieve Album id 1
            value: 1
          two:
            summary: Retrieve Album id 2
            value: 2
      responses:
        "200":
          description: Show Album with ID
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Musica'
                x-content-type: application/json
            application/xml:
              schema:
                $ref: '#/components/schemas/inline_response_200_Musica'
      x-swagger-router-controller: Albums
  /Albums{id}:
    delete:
      tags:
      - Albums
      summary: Delete Album
      operationId: deleteAlbum
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Delete Album id 1
            value: 1
          two:
            summary: Delete Album id 2
            value: 2
      responses:
        "204":
          description: No Content
        "404":
          description: id not found
      x-swagger-router-controller: AlbumsController
  /Artista:
    get:
      tags:
      - Artistas
      summary: retrieve Artistas
      operationId: retrieveArtista
      responses:
        "200":
          description: Array of all Artistas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Artista'
                x-content-type: application/json
            application/xml:
              schema:
                $ref: '#/components/schemas/inline_response_200_Artista'
        x-swagger-router-controller: Artistas
      x-swagger-router-controller: Artistas
    post:
      tags:
      - Artistas
      summary: Create Artista
      operationId: createArtista
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Artista'
            examples:
              MusicaExample01:
                $ref: '#/components/examples/ArtistaExample01'
              MusicaExample02:
                $ref: '#/components/examples/ArtistaExample02'
          application/xml:
            schema:
              $ref: '#/components/schemas/Artista'
            examples:
              MusicaExample01:
                $ref: '#/components/examples/ArtistaExample01'
              MusicaExample02:
                $ref: '#/components/examples/ArtistaExample02'
      responses:
        "200":
          description: Create a Artista
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artista'
            application/xml:
              schema:
                $ref: '#/components/schemas/Artista'
        "400":
          description: Bad request
      x-swagger-router-controller: Artistas
  /Artistas/{id}:
    get:
      tags:
      - Artistas
      summary: retrieve Artista with ID
      operationId: retrieveArtistaID
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Retrieve Artista id 1
            value: 1
          two:
            summary: Retrieve Artista id 2
            value: 2
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artista'
            application/xml:
              schema:
                $ref: '#/components/schemas/Artista'
        "400":
          description: Bad request
        "404":
          description: id not found
      x-swagger-router-controller: Artistas
    put:
      tags:
      - Artistas
      summary: Update Artista
      operationId: updateArtista
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Update Artista id 1
            value: 1
          two:
            summary: Update Artista id 2
            value: 2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Artista'
            examples:
              Example01:
                $ref: '#/components/examples/ArtistaExample01'
              Example02:
                $ref: '#/components/examples/ArtistaExample02'
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                description: Artista PUT success
                x-content-type: application/json
        "400":
          description: Bad request
        "404":
          description: id not found
      x-swagger-router-controller: Artistas
    delete:
      tags:
      - Artistas
      summary: Delete Artista
      operationId: deleteArtista
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Delete Artista id 1
            value: 1
          two:
            summary: Delete Artista id 2
            value: 2
      responses:
        "204":
          description: No Content
        "404":
          description: id not found
      x-swagger-router-controller: Artistas
  /User:
    get:
      tags:
      - Users
      summary: retrieve Users
      operationId: retrieveUsers
      responses:
        "200":
          description: retrieve all users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
                x-content-type: application/json
            application/xml:
              schema:
                $ref: '#/components/schemas/inline_response_200_User'
        x-swagger-router-controller: Users
      x-swagger-router-controller: Users
    post:
      tags:
      - Users
      summary: Create User
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              UserExample01:
                $ref: '#/components/examples/UserExample01'
              UserExample02:
                $ref: '#/components/examples/UserExample02'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              UserExample01:
                $ref: '#/components/examples/UserExample01'
              UserExample02:
                $ref: '#/components/examples/UserExample02'
      responses:
        "200":
          description: Create a User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: Bad request
      x-swagger-router-controller: Users
  /Users/{id}:
    get:
      tags:
      - Users
      summary: retrieve Users with ID
      operationId: retrieveUsersID
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Retrieve User id 1
            value: 1
          two:
            summary: Retrieve User id 2
            value: 2
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: Bad request
        "404":
          description: id not found
      x-swagger-router-controller: Users
    put:
      tags:
      - Users
      summary: Update User
      operationId: updateUser
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Update User id 1
            value: 1
          two:
            summary: Update User id 2
            value: 2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              Example01:
                $ref: '#/components/examples/UserExample01'
              Example02:
                $ref: '#/components/examples/UserExample02'
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                description: User PUT success
                x-content-type: application/json
        "400":
          description: Bad request
        "404":
          description: id not found
      x-swagger-router-controller: Users
    delete:
      tags:
      - Users
      summary: Delete User
      operationId: deleteUser
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Delete User id 1
            value: 1
          two:
            summary: Delete User id 2
            value: 2
      responses:
        "204":
          description: No Content
        "404":
          description: id not found
      x-swagger-router-controller: Users
components:
  schemas:
    Album:
      title: Album
      required:
      - nomealbum
      - nomeartista
      type: object
      properties:
        id:
          type: integer
          format: int64
        nomealbum:
          type: string
        nomeartista:
          type: string
      additionalProperties: false
      example:
        nomealbum: nomealbum
        nomeartista: nomeartista
    Musica:
      title: Musica
      required:
      - nomeMusica
      - nomeartista
      type: object
      properties:
        id:
          type: integer
          format: int64
        genero:
          type: string
        nomeartista:
          type: string
        nomeMusica:
          type: string
        datadelancamento:
          type: integer
          format: int64
        album_id:
          type: integer
          format: int64
      additionalProperties: false
      example:
        genero: genero
        nomeartista: nomeartista
        nomeMusica: Musica
    Artista:
      title: Artista
      required:
      - nomeartista
      type: object
      properties:
        id:
          type: integer
          format: int64
        nomeartista:
          type: string
        pais:
          type: string
      additionalProperties: false
      example:
        nomeartista: nomeartista
        pais: pais
    User:
      title: User
      required:
      - email
      - pais
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        pais:
          type: string
        idade:
          type: integer
          format: int64
        email:
          type: string
      additionalProperties: false
      example:
        nome: nome
        pais: pais
        idade: idade
        email: email
    inline_response_200_Musica:
      type: object
      properties:
        Musica:
          type: array
          items:
            $ref: '#/components/schemas/Musica'
      xml:
        name: Musica
    inline_response_200_Album:
      type: object
      properties:
        Album:
          type: array
          items:
            $ref: '#/components/schemas/Album'
      xml:
        name: Albums
    inline_response_200_Artista:
      type: object
      properties:
        Artista:
          type: array
          items:
            $ref: '#/components/schemas/Artista'
      xml:
        name: Artistas
    inline_response_200_User:
      type: object
      properties:
        User:
          type: array
          items:
            $ref: '#/components/schemas/User'
      xml:
        name: Users
  examples:
    AlbumExample01:
      value:
        id: 1
        nomealbum: "Yasmin Williams: Urban Driftwood"
        nomeartista: Quinn
    AlbumExample02:
      value:
        id: 2
        nomealbum: "Magdalena Bay: Mercurial World"
        nomeartista: Eric Torres
    MusicaExample01:
      value:
        id: 1
        genero: POP
        nomeartista: testenomeartista
        nomeMusica: Cant Get You Out Of My Head
        datadelancamento: 2000
    MusicaExample02:
      value:
        id: 2
        genero: Rock
        nomeartista: Queen
        nomeMusica: Don't Stop Me Now
        datadelancamento: 2001
    ArtistaExample01:
      value:
        id: 1
        nomeartista: Matue
        pais: Brasil
    ArtistaExample02:
      value:
        id: 2
        nomeartista: Teto
        pais: Brasil
    UserExample01:
      value:
        id: 1
        nome: Pedro
        pais: Portugal
        idade: 30
        email: pedro@gmail.com
    UserExample02:
      value:
        id: 2
        nome: Carlos
        pais: Portugal
        idade: 20
        email: carlos@gmail.com
